# Generated by Django 2.0.4 on 2018-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafoli', '0002_auto_20180702_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='urlmoreinf',
            field=models.URLField(blank=True, null=True, verbose_name='direccio web'),
        ),
    ]
